## 00. pytorch fundamentals

In [99]:
import torch
#import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [5]:
print(torch.__version__)

2.0.0+cu118


In [114]:
!nvidia-smi

Wed May  3 22:26:45 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.49       Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:11:00.0  On |                  N/A |
| 29%   39C    P8    21W / 125W |   2031MiB /  6144MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to tensors

### Creating tensors

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.shape

torch.Size([2])

In [13]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [25]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0639, 0.8331, 0.8352, 0.0427],
        [0.9966, 0.7566, 0.9921, 0.9372],
        [0.3695, 0.4854, 0.1993, 0.4350]])

In [26]:
random_tensor.ndim

2

In [29]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [30]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [36]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [37]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [39]:
# Float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # float32 or float16
                               device=None, # cpu or cuda
                               requires_grad=False) # whether to track gradiance with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor.dtype

torch.float32

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

In [42]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1303, 0.2987, 0.5064, 0.9280],
        [0.6417, 0.1055, 0.5611, 0.0979],
        [0.2729, 0.3923, 0.5302, 0.9953]])

In [43]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1303, 0.2987, 0.5064, 0.9280],
        [0.6417, 0.1055, 0.5611, 0.0979],
        [0.2729, 0.3923, 0.5302, 0.9953]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulatin Tensors (tensor operations)

operations:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [44]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [45]:
tensor * 10

tensor([10, 20, 30])

In [46]:
tensor - 10

tensor([-9, -8, -7])

In [47]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [48]:
# Equal to *
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication (dot product)

In [49]:
# Element-wise
tensor * tensor

tensor([1, 4, 9])

In [50]:
# Matrix mult
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors - shape error
1. The inner dimensions must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the outer dimensions

In [56]:
%%time
tensor_A = torch.tensor([[3, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B.T)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc (tensor aggregations)

In [57]:
x = torch.arange(0, 100, 10)
x.min()

tensor(0)

In [58]:
x.max()

tensor(90)

In [62]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [63]:
x.sum()

tensor(450)

### Finding the positional min and max

In [71]:
tensor_A = torch.tensor([[3, 2],
                         [3, 4],
                         [5, 6]])

In [72]:
tensor_A.argmin()

tensor(1)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [76]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [78]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [80]:
z = x.view(5,2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [82]:
z[2, :] = 110
z

tensor([[  1.,   2.],
        [  3.,   4.],
        [110., 110.],
        [  7.,   8.],
        [  9.,  10.]])

In [85]:
# Stack tensors on top
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[  1.,   1.,   1.,   1.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [110., 110., 110., 110.],
        [110., 110., 110., 110.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.],
        [ 10.,  10.,  10.,  10.]])

In [89]:
x

tensor([  1.,   2.,   3.,   4., 110., 110.,   7.,   8.,   9.,  10.])

In [88]:
x.squeeze()

tensor([  1.,   2.,   3.,   4., 110., 110.,   7.,   8.,   9.,  10.])

In [91]:
x.unsqueeze(dim=0)

tensor([[  1.,   2.,   3.,   4., 110., 110.,   7.,   8.,   9.,  10.]])

In [92]:
x.unsqueeze(dim=0).permute(1, 0)

tensor([[  1.],
        [  2.],
        [  3.],
        [  4.],
        [110.],
        [110.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.]])

## Indexing (selecting data from tensors)

In [93]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [94]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
x[0][0]

tensor([1, 2, 3])

In [96]:
x[0][0][0]

tensor(1)

In [98]:
x[:, :, 0]

tensor([[1, 4, 7]])

## PyTorch tensors & NumPy

In [101]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
To reduce the randomnes use fixed seed

In [103]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7390, 0.8117, 0.1460, 0.6425],
        [0.1972, 0.7409, 0.2507, 0.8437],
        [0.6822, 0.3293, 0.6474, 0.4769]])
tensor([[0.6653, 0.4311, 0.3626, 0.6288],
        [0.3464, 0.3885, 0.9576, 0.3158],
        [0.0413, 0.8975, 0.0015, 0.9353]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [105]:
RANDOM_SEED = 2324546

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.7449, 0.1945, 0.8183, 0.9378],
        [0.7610, 0.4194, 0.1919, 0.0123],
        [0.9284, 0.6633, 0.1718, 0.0800]])
tensor([[0.7449, 0.1945, 0.8183, 0.9378],
        [0.7610, 0.4194, 0.1919, 0.0123],
        [0.9284, 0.6633, 0.1718, 0.0800]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs

In [106]:
# Check for GPU access in PyTorch
torch.cuda.is_available()

True

In [109]:
# Setuo device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [108]:
torch.cuda.device_count()

1

In [110]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1., 1., 1., 1., 1., 1., 1.], device='cuda:0')

In [115]:
tensor_back_on_cpu = tensor_on_gpu.cpu()

In [116]:
tensor_back_on_cpu.device

device(type='cpu')