## 00. pytorch fundamentals

In [2]:
import torch
#import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


In [3]:
print(torch.__version__)

2.0.0+cpu


In [4]:
!nvidia-smi

"nvidia-smi" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.


## Introduction to tensors

### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2364, 0.2208, 0.4136, 0.8544],
        [0.4468, 0.0320, 0.3145, 0.3889],
        [0.9836, 0.3251, 0.8537, 0.0400]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [26]:
# Float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # float32 or float16
                               device=None, # cpu or cuda
                               requires_grad=False) # whether to track gradiance with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

In [29]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3577, 0.7356, 0.6527, 0.6618],
        [0.2512, 0.9005, 0.8909, 0.9376],
        [0.6809, 0.2097, 0.6644, 0.7834]])

In [30]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3577, 0.7356, 0.6527, 0.6618],
        [0.2512, 0.9005, 0.8909, 0.9376],
        [0.6809, 0.2097, 0.6644, 0.7834]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulatin Tensors (tensor operations)

operations:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor - 10

tensor([-9, -8, -7])

In [34]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [35]:
# Equal to *
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication (dot product)

In [36]:
# Element-wise
tensor * tensor

tensor([1, 4, 9])

In [37]:
# Matrix mult
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors - shape error
1. The inner dimensions must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the outer dimensions

In [38]:
%%time
tensor_A = torch.tensor([[3, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B.T)

CPU times: total: 0 ns
Wall time: 1.52 ms


tensor([[ 41,  46,  51],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc (tensor aggregations)

In [39]:
x = torch.arange(0, 100, 10)
x.min()

tensor(0)

In [40]:
x.max()

tensor(90)

In [41]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [42]:
x.sum()

tensor(450)

### Finding the positional min and max

In [43]:
tensor_A = torch.tensor([[3, 2],
                         [3, 4],
                         [5, 6]])

In [44]:
tensor_A.argmin()

tensor(1)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [45]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [46]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [47]:
z = x.view(5,2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [48]:
z[2, :] = 110
z

tensor([[  1.,   2.],
        [  3.,   4.],
        [110., 110.],
        [  7.,   8.],
        [  9.,  10.]])

In [49]:
# Stack tensors on top
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[  1.,   1.,   1.,   1.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [110., 110., 110., 110.],
        [110., 110., 110., 110.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.],
        [ 10.,  10.,  10.,  10.]])

In [50]:
x

tensor([  1.,   2.,   3.,   4., 110., 110.,   7.,   8.,   9.,  10.])

In [51]:
x.squeeze()

tensor([  1.,   2.,   3.,   4., 110., 110.,   7.,   8.,   9.,  10.])

In [52]:
x.unsqueeze(dim=0)

tensor([[  1.,   2.,   3.,   4., 110., 110.,   7.,   8.,   9.,  10.]])

In [53]:
x.unsqueeze(dim=0).permute(1, 0)

tensor([[  1.],
        [  2.],
        [  3.],
        [  4.],
        [110.],
        [110.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.]])

## Indexing (selecting data from tensors)

In [54]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
x[0][0]

tensor([1, 2, 3])

In [57]:
x[0][0][0]

tensor(1)

In [58]:
x[:, :, 0]

tensor([[1, 4, 7]])

## PyTorch tensors & NumPy

In [59]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
To reduce the randomnes use fixed seed

In [61]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2433, 0.7743, 0.5941, 0.2933],
        [0.8286, 0.8476, 0.6595, 0.3555],
        [0.4354, 0.3482, 0.0970, 0.5224]])
tensor([[7.1001e-01, 2.2673e-01, 5.4245e-01, 6.5821e-01],
        [8.8059e-01, 9.7507e-04, 1.6013e-01, 9.5474e-01],
        [6.3257e-01, 4.5894e-01, 6.7758e-01, 9.9790e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [62]:
RANDOM_SEED = 2324546

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.7449, 0.1945, 0.8183, 0.9378],
        [0.7610, 0.4194, 0.1919, 0.0123],
        [0.9284, 0.6633, 0.1718, 0.0800]])
tensor([[0.7449, 0.1945, 0.8183, 0.9378],
        [0.7610, 0.4194, 0.1919, 0.0123],
        [0.9284, 0.6633, 0.1718, 0.0800]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs

In [63]:
# Check for GPU access in PyTorch
torch.cuda.is_available()

False

In [64]:
# Setuo device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [65]:
torch.cuda.device_count()

0

In [66]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1., 1., 1., 1., 1., 1., 1.])

In [67]:
tensor_back_on_cpu = tensor_on_gpu.cpu()

In [68]:
tensor_back_on_cpu.device

device(type='cpu')